export { default as DashboardIcon } from "./dashboard";
export { default as RepairmentIcon } from "./repairment";
export { default as DownArrowIcon } from "./down-arrow";
export { default as SettingsIcon } from "./settings";
export { default as NotificationIcon } from "./notification";
export { default as StorageIcon } from "./storage";
export { default as ManIcon } from "./man";
export { default as PaymentIcon } from "./payment";
export { default as LogoutIcon } from "./logout";
