export const titles = {
  "/dashboard": "Dashboard",
  "/repairments": "Repairments",
  "/repairments/assigned-repairments": "Assigned Repairments",
  "/repairments/create-repairment": "Create New Repairment",
  "/repairments/list-repairments": "List Repairments",
  "/employees": "Employees",
  "/employees/employee-stats": "Employee Stats",
  "/employees/list-employees": "Employee List",
  "/employees/register-employee": "Register New Employee",
  "/payments": "Payments",
  "/payments/list-payments": "Payment List",
  "/payments/new-payment": "Add New Payment",
  "/storage": "Storage",
  "/storage/add-part": "Add New Part",
  "/storage/list-orders": "Order List",
  "/storage/list-parts": "Part List",
  "/storage/new-order": "Add New Order",
};
